(() => {
const canvas=document.getElementById('pista'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,$=id=>document.getElementById(id);let ROAD_X=40,ROAD_W=280;
const cars=[
{id:'turbo',name:'Turbo',emoji:'🏎️',cor:'#e63946',vel:1.12,controle:1.05,resistencia:1,preco:0,desc:'Equilibrado e rápido.'},
{id:'sport',name:'Sport',emoji:'🚗',cor:'#2a9df4',vel:1.28,controle:.95,resistencia:.9,preco:450,desc:'Muito veloz, controle menor.'},
{id:'offroad',name:'Off-Road',emoji:'🚙',cor:'#2ecc71',vel:.98,controle:1.18,resistencia:1.35,preco:700,desc:'Resistente e fácil de controlar.'},
{id:'super',name:'Super',emoji:'🏁',cor:'#9b5de5',vel:1.42,controle:1,resistencia:.85,preco:1200,desc:'Velocidade máxima.'}
];
const colors=['#e63946','#2a9df4','#ffc107','#2ecc71','#9b5de5','#f5f5f5','#ff6b35','#00c2a8'];
const shop=[{id:'turbo',name:'⚡ Turbo extra',price:300,desc:'Começa a próxima corrida com um turbo (uso único).'},{id:'shield',name:'🛡️ Escudo',price:500,desc:'Aguenta uma colisão na próxima corrida (uso único).'},{id:'magnet',name:'🧲 Ímã',price:650,desc:'Atrai moedas e itens próximos (permanente).',perm:true},{id:'coin2',name:'🪙 Multiplicador',price:800,desc:'Moedas valem o dobro (permanente).',perm:true}];
const achievements=[['primeira','Primeira corrida','Faça sua primeira corrida.'],['mil','Piloto','Alcance 1.000 pontos.'],['cinco','Velocista','Alcance 5.000 pontos.'],['coins','Colecionador','Pegue 50 moedas em uma corrida.'],['turbo','Turbo','Use 3 turbos.'],['longe','Sobrevivente','Passe de 120 segundos.']];
const tracks={campo:{nome:'Campo verde',grass:'#5aa14a',tree:'#2f6b2a',road:'#3b3f45',dens:1,spd:.9,rw:280},litoral:{nome:'Litoral',grass:'#36a6a0',tree:'#176d73',road:'#424b52',dens:1.3,spd:1,rw:260},deserto:{nome:'Deserto',grass:'#c99b4a',tree:'#8b612d',road:'#4a4541',dens:1.7,spd:1.1,rw:240},cidade:{nome:'Cidade',grass:'#3a3e45',tree:'#252a30',road:'#292d33',dens:2.2,spd:1.25,rw:210}};
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function difLabel(t){const d=(t.dens-.8)/1.6*.4+(t.spd-.8)/.6*.35+(280-t.rw)/80*.25;return d<.25?'Fácil':d<.5?'Médio':d<.75?'Difícil':'Extremo'}
const cfg={cor:cars[0].cor,obs:'mistos',track:'campo',mode:'infinito'};
let save={coins:0,selected:'turbo',owned:['turbo'],best:0,color:null,custom:[],totalRaces:0,totalCoins:0,turbos:0,time:0,ach:{}},state='inicio',obs=[],pickups=[],decor=[],score=0,raceCoins=0,speed=220,time=0,spawn=0,pickupSpawn=1,shield=false,turbo=0,magnet=false,boost=1,last=0,roadOffset=0,level=1,weather='normal',audio=true,audioCtx=null,rafId=0,lives=1,magnetT=0,weatherT=0,boostT=0,trafficT=0,eventT=6,dodged=0,nitro=100,nitroOn=false,nitroLock=0,fx=[];
try{Object.assign(save,JSON.parse(localStorage.getItem('corrida-save')||'{}'));}catch(e){};save.ach=save.ach||{};save.owned=save.owned||['turbo'];if(save.color)cfg.cor=save.color;if(!Array.isArray(save.custom))save.custom=[];save.custom.forEach(t=>tracks[t.id]=t);$('recorde').textContent=save.best;$('moedas').textContent=save.coins;
function persist(){try{localStorage.setItem('corrida-save',JSON.stringify(save));}catch(e){}}
function sound(freq,d=.1,type='sine',v=.06){if(!audio)return;try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audioCtx ||= new A();if(audioCtx.state==='suspended')audioCtx.resume();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(v,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(e){}}
function toast(msg){const e=$('evento');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
function mark(group,target,selector='.chip'){group.querySelectorAll(selector).forEach(x=>x.classList.remove('ativo'));target.classList.add('ativo')}
function previewCar(){const c=cars.find(x=>x.id===save.selected)||cars[0];$('carroGrande').style.color=cfg.cor;$('nomeCarro').textContent=c.name;$('carroPrep').style.color=cfg.cor;$('nomePrep').textContent=c.name}
function renderGarage(){previewCar();
$('carros').innerHTML=cars.map(c=>`<div class="card ${save.selected===c.id?'selecionado':''}"><div class="car-preview"><svg viewBox="0 0 300 110" style="color:${save.selected===c.id?cfg.cor:c.cor}"><use href="#carro" width="100%" height="100%"/></svg></div><h3>${c.name}</h3><p class="muted">${c.desc}</p><p>Velocidade: ${(c.vel*100).toFixed(0)}%<br>Controle: ${(c.controle*100).toFixed(0)}%<br>Resistência: ${(c.resistencia*100).toFixed(0)}%</p><button class="btn ${save.owned.includes(c.id)?'':'buy'}" data-car="${c.id}">${save.owned.includes(c.id)?(save.selected===c.id?'Selecionado':'Usar'):`Comprar 🪙 ${c.preco}`}</button></div>`).join('');
$('carros').querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>{let c=cars.find(x=>x.id===b.dataset.car);if(save.owned.includes(c.id)){save.selected=c.id;cfg.cor=save.color=c.cor;draw();persist();renderGarage();toast(c.name+' selecionado!')}else if(save.coins>=c.preco){save.coins-=c.preco;save.owned.push(c.id);save.selected=c.id;cfg.cor=save.color=c.cor;draw();persist();ui();renderGarage();toast('Carro desbloqueado!')}else toast('Moedas insuficientes.')});
$('cores').innerHTML=colors.map(c=>`<button class="cor ${cfg.cor===c?'ativo':''}" style="background:${c}" data-cor="${c}"></button>`).join('');$('cores').querySelectorAll('[data-cor]').forEach(b=>b.onclick=()=>{cfg.cor=save.color=b.dataset.cor;persist();renderGarage();draw()});
}
function renderShop(){$('saldoLoja').textContent=save.coins;$('itensLoja').innerHTML=shop.map(i=>{const own=!!save[i.id];return `<div class="card"><h3>${i.name}</h3><p class="muted">${i.desc}</p><button class="btn" data-item="${i.id}" ${own?'disabled':''}>${own?(i.perm?'✅ Comprado':'✅ Em estoque'):'Comprar 🪙 '+i.price}</button></div>`}).join('');$('itensLoja').querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{let i=shop.find(x=>x.id===b.dataset.item);if(save[i.id])return;if(save.coins<i.price)return toast('Moedas insuficientes.');save.coins-=i.price;save[i.id]=true;persist();ui();renderShop();toast(i.name+' comprado!')})}
function renderProfile(){const a=save.ach;$('statsPerfil').innerHTML=[['Corridas',save.totalRaces],['Maior pontuação',save.best],['Moedas ganhas',save.totalCoins],['Turbos usados',save.turbos],['Tempo total',Math.floor(save.time)+'s'],['Carros',save.owned.length+'/'+cars.length]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('conquistas').innerHTML=achievements.map(x=>`<div class="conquista ${a[x[0]]?'ok':''}"><b>${a[x[0]]?'✅':'🔒'} ${x[1]}</b><div class="muted">${x[2]}</div></div>`).join('');$('recordesLista').innerHTML=`<div class="card">🏆 Melhor pontuação: <b>${save.best}</b><br>🏎️ Melhor carro: ${cars.find(c=>c.id===save.selected)?.name||'Turbo'}</div>`}
function ui(){const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};set('moedas',save.coins);set('saldoLoja',save.coins);set('recorde',save.best);set('hRec',save.best);set('tRec',save.best);set('hMoe',save.coins);set('tempo',Math.floor(time)+'s');set('nivel',level)}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{if(state==='jogando')pause();document.querySelectorAll('.tab').forEach(x=>x.classList.remove('ativo'));document.querySelectorAll('.aba').forEach(x=>x.classList.remove('ativa'));b.classList.add('ativo');$(b.dataset.tab).classList.add('ativa');if(b.dataset.tab==='garagem')renderGarage();if(b.dataset.tab==='loja')renderShop();if(b.dataset.tab==='perfil')renderProfile()});

document.querySelectorAll('[data-obs]').forEach(b=>b.onclick=()=>{cfg.obs=b.dataset.obs;mark($('opObs'),b)});document.querySelectorAll('[data-modo]').forEach(b=>b.onclick=()=>{cfg.mode=b.dataset.modo;mark($('opModo'),b)});$('btnSom').onclick=()=>{audio=!audio;$('btnSom').textContent=(audio?'Som: ligado':'Som: desligado');if(audio)sound(660,.1)};
const keys={esq:0,dir:0,cima:0,baixo:0,nitro:0};const map={ArrowLeft:'esq',a:'esq',A:'esq',ArrowRight:'dir',d:'dir',D:'dir',ArrowUp:'cima',w:'cima',W:'cima',ArrowDown:'baixo',s:'baixo',S:'baixo', ' ':'nitro',Shift:'nitro',n:'nitro',N:'nitro'};
addEventListener('keydown',e=>{if(/^(SELECT|INPUT|TEXTAREA)$/.test(e.target.tagName))return;const onRace=$('corrida').classList.contains('ativa');let k=map[e.key];if(k){keys[k]=1;e.preventDefault()}if((e.key==='p'||e.key==='P')&&onRace)pause();});
addEventListener('keyup',e=>{let k=map[e.key];if(k)keys[k]=0});
addEventListener('blur',()=>{for(const k in keys)keys[k]=0;if(state==='jogando')pause()});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='jogando')pause()});
document.querySelectorAll('[data-tecla]').forEach(b=>{let k=b.dataset.tecla;b.onpointerdown=e=>{keys[k]=1;e.preventDefault()};['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys[k]=0))});
let car={x:W/2-18,y:H-92,w:36,h:62};
function reset(){obs=[];pickups=[];decor=[];score=0;raceCoins=0;time=0;speed=0;spawn=1.5;pickupSpawn=.8;roadOffset=0;level=1;weather='normal';shield=!!save.shield;turbo=save.turbo?1:0;magnet=!!save.magnet;boost=1;lives=((cars.find(x=>x.id===save.selected)||cars[0]).resistencia>1.2)?2:1;dodged=0;nitro=100;nitroOn=false;nitroLock=0;fx=[];magnetT=0;weatherT=0;boostT=0;trafficT=0;eventT=6;car.x=W/2-car.w/2;car.y=H-car.h-50;for(let i=0;i<22;i++)decor.push({x:decorX(),y:Math.random()*H,r:8+Math.random()*7});ui()}
function run(){cancelAnimationFrame(rafId);rafId=requestAnimationFrame(loop)}
function start(){if(document.activeElement&&document.activeElement.blur)document.activeElement.blur();applyTrack();reset();if(save.shield||save.turbo){save.shield=false;save.turbo=false;persist()}state='jogando';$('telaInicio').hidden=true;$('telaFim').hidden=true;$('telaPausa').hidden=true;last=performance.now();sound(520,.12);run()}
function pause(){if(state==='jogando'){state='pausa';$('telaPausa').hidden=false}else if(state==='pausa'){state='jogando';$('telaPausa').hidden=true;last=performance.now();run()}}
function createObstacle(){let t=cfg.obs;if(t==='mistos')t=['cones','pedras','carros'][Math.floor(Math.random()*3)];let d={cones:[28,32],pedras:[40,34],carros:[36,62]}[t],x=ROAD_X+8+Math.random()*(ROAD_W-d[0]-16);obs.push({type:t,x,y:-d[1],w:d[0],h:d[1],color:['#d94141','#2979ff','#9c65d1'][Math.floor(Math.random()*3)]})}
function createPickup(){const r=Math.random(),x=ROAD_X+6+Math.random()*(ROAD_W-32);if(r<.4){for(let i=0;i<4;i++)pickups.push({type:'coin',x,y:-25-i*34,w:20,h:20});return}pickups.push({type:r<.85?'coin':['turbo','shield','magnet'][Math.floor(Math.random()*3)],x,y:-25,w:20,h:20})}
function overlap(a,b,m=3){return a.x+m<b.x+b.w-m&&a.x+a.w-m>b.x+m&&a.y+m<b.y+b.h-m&&a.y+a.h-m>b.y+m}
function event(dt){eventT-=dt;if(eventT>0)return;eventT=8+Math.random()*10;const r=Math.random();if(r<.3){weather='rain';weatherT=8;toast('🌧️ Chuva! Obstáculos mais rápidos.')}else if(r<.55){trafficT=7;toast('🚦 Trânsito intenso!')}else if(r<.8){weather='normal';weatherT=0;toast('☀️ Céu limpo!')}else{boostT=4;toast('⚡ Turbina de velocidade!');sound(700,.2,'triangle')}}
function update(dt){let c=cars.find(x=>x.id===save.selected)||cars[0],control=250*c.controle;let dir=(keys.dir?1:0)-(keys.esq?1:0);car.x+=dir*control*dt;car.x=Math.max(ROAD_X+3,Math.min(ROAD_X+ROAD_W-car.w-3,car.x));car.y=Math.max(H*.32,Math.min(H-car.h-46,car.y));
nitroStep(dt);weatherT-=dt;if(weatherT<=0&&weather==='rain')weather='normal';boostT-=dt;boost=boostT>0?1.35:1;trafficT-=dt;
if(turbo>0)turbo-=dt;
const base=Math.min(440,(230+Math.min(170,score*.06))*c.vel*tracks[cfg.track].spd),cap=Math.min(600,base*(1+(nitroOn?.35:0)+(turbo>0?.2:0)+(boost>1?.15:0)));
if(keys.baixo)speed-=320*dt;else if(keys.cima||nitroOn)speed+=(nitroOn?420:150)*c.controle*dt;else speed-=45*dt;
if(speed>cap)speed=Math.max(cap,speed-260*dt);speed=Math.max(0,speed);time+=dt;save.time+=dt;level=Math.floor(score/1000)+1;roadOffset=(roadOffset+speed*dt)%60;score+=speed*dt*.065;const sf=Math.min(1.6,speed/250);spawn-=dt*sf;pickupSpawn-=dt*sf;if(spawn<=0){createObstacle();spawn=Math.max(.32,1.05-score/1000)*(0.75+Math.random()*.4)*(trafficT>0?.6:1)/tracks[cfg.track].dens}if(pickupSpawn<=0){createPickup();pickupSpawn=1+Math.random()*1.2}
obs.forEach(o=>o.y+=speed*dt*(weather==='rain'?1.08:1));dodged+=obs.filter(o=>o.y>=H+90&&!o.hit).length;obs=obs.filter(o=>o.y<H+90);pickups.forEach(p=>p.y+=speed*dt);pickups=pickups.filter(p=>p.y<H+40);decor.forEach(d=>d.y+=speed*dt*.7);decor=decor.filter(d=>d.y<H+30);if(decor.length<23)decor.push({x:decorX(),y:-25,r:8+Math.random()*7});
for(const o of obs)if(overlap(car,o)){if(shield){shield=false;toast('🛡️ Escudo absorveu a batida!');o.hit=true;o.y=H+100;sound(180,.2,'square')}else if(lives>1){lives--;toast('💥 Batida! Seu carro resistiu.');o.hit=true;o.y=H+100;sound(180,.2,'square')}else{gameOver();return}}
for(const p of pickups)if(overlap(car,p,0)){if(p.type==='coin'){let val=save.coin2?2:1;raceCoins+=val;score+=100*val;sound(880,.08);p.y=H+100}else if(p.type==='turbo'){turbo=2;nitro=Math.min(100,nitro+40);save.turbos++;toast('⚡ TURBO!');sound(700,.2,'triangle');p.y=H+100}else if(p.type==='shield'){shield=true;toast('🛡️ ESCUDO!');p.y=H+100;sound(500,.2)}else{magnetT=6;toast('🧲 ÍMÃ!');sound(500,.2);p.y=H+100}}
if(magnetT>0)magnetT-=dt;if(magnet||magnetT>0)pickups.forEach(p=>{let dx=car.x+car.w/2-(p.x+p.w/2);if(Math.abs(dx)<110&&car.y-p.y<240&&p.y>-20)p.x+=Math.sign(dx)*Math.min(Math.abs(dx),150*dt)});event(dt);if(cfg.mode==='tempo'&&time>=60)gameOver(true,'⏱️ Tempo esgotado!');if(cfg.mode==='desafio'&&score>=1500)gameOver(true);ui()}
function gameOver(win=false,msg=''){if(state==='fim')return;state='fim';let p=Math.floor(score),isNew=p>save.best&&p>0;save.totalRaces++;save.totalCoins+=raceCoins;save.coins+=raceCoins;if(p>save.best)save.best=p;save.ach.primeira=true;if(p>=1000)save.ach.mil=true;if(p>=5000)save.ach.cinco=true;if(raceCoins>=50)save.ach.coins=true;if(save.turbos>=3)save.ach.turbo=true;if(time>=120)save.ach.longe=true;persist();$('pontosFinal').textContent=p;$('resumoFinal').innerHTML=`<div class="tile"><span>Moedas</span><b>${raceCoins}</b></div><div class="tile"><span>Tempo</span><b>${Math.floor(time)}s</b></div><div class="tile"><span>Nível</span><b>${level}</b></div><div class="tile"><span>Desviados</span><b>${dodged}</b></div>`+(win?`<div class="tile largo">${esc(msg||'Desafio concluído!')}</div>`:'');$('recordeMsg').textContent=isNew?'Novo recorde!':'Recorde: '+save.best;$('telaFim').hidden=false;sound(win?900:150,.35,win?'triangle':'sawtooth',.1);ui()}
function rr(x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);ctx.fill()}
function carDraw(x,y,w,h,color,front=true){ctx.fillStyle='#101010';rr(x-3,y+9,5,14,2);rr(x+w-2,y+9,5,14,2);rr(x-3,y+h-23,5,14,2);rr(x+w-2,y+h-23,5,14,2);ctx.fillStyle=color;rr(x,y,w,h,9);ctx.fillStyle='#172b3a';rr(x+5,y+12,w-10,18,4);ctx.fillStyle='#ffffffaa';rr(x+7,y+34,w-14,6,2);ctx.fillStyle=front?'#fff4b0':'#ef5350';rr(x+3,y+2,8,4,2);rr(x+w-11,y+2,8,4,2)}
function obstacleDraw(o){if(o.type==='cones'){ctx.fillStyle='#ff6a00';ctx.beginPath();ctx.moveTo(o.x+o.w/2,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.lineTo(o.x,o.y+o.h);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(o.x+5,o.y+o.h*.45,o.w-10,5)}else if(o.type==='pedras'){ctx.fillStyle='#777e89';ctx.beginPath();ctx.moveTo(o.x,o.y+o.h);ctx.lineTo(o.x+4,o.y+8);ctx.lineTo(o.x+o.w*.6,o.y);ctx.lineTo(o.x+o.w,o.y+o.h*.55);ctx.closePath();ctx.fill()}else carDraw(o.x,o.y,o.w,o.h,o.color,false)}
function drawScene(){let t=tracks[cfg.track];ctx.fillStyle=t.grass;ctx.fillRect(0,0,W,H);decor.forEach(d=>{ctx.fillStyle=t.tree;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill();ctx.fillRect(d.x-2,d.y,d.r/2,13)});ctx.fillStyle=t.road;ctx.fillRect(ROAD_X,0,ROAD_W,H);ctx.fillStyle='#d5bd55';ctx.fillRect(ROAD_X-4,0,4,H);ctx.fillRect(ROAD_X+ROAD_W,0,4,H);ctx.fillStyle='#eee';for(let y=-60+roadOffset;y<H;y+=60){ctx.fillRect(W/2-3,y,6,30);ctx.fillRect(ROAD_X+ROAD_W/3-2,y,4,30);ctx.fillRect(ROAD_X+2*ROAD_W/3-2,y,4,30)}obs.forEach(obstacleDraw);pickups.forEach(p=>{const cx=p.x+p.w/2,cy=p.y+p.h/2;ctx.textAlign='center';if(p.type==='coin'){ctx.shadowColor='#ffc93c';ctx.shadowBlur=14;ctx.fillStyle='#ffc93c';ctx.beginPath();ctx.arc(cx,cy,9,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#a8741a';ctx.font='bold 12px Arial';ctx.fillText('$',cx,cy+4)}else{ctx.font='21px Arial';ctx.fillText(p.type==='turbo'?'⚡':p.type==='shield'?'🛡️':'🧲',cx,p.y+17)}});drawFx();carDraw(car.x,car.y,car.w,car.h,cfg.cor,true);if(shield){ctx.strokeStyle='#42a5f5';ctx.lineWidth=3;ctx.beginPath();ctx.arc(car.x+car.w/2,car.y+car.h/2,car.h*.68,0,Math.PI*2);ctx.stroke()}if(weather==='rain'){ctx.strokeStyle='#9ec5ff66';ctx.lineWidth=1;for(let i=0;i<70;i++){let x=(i*37)%W,y=(i*71+roadOffset*2)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+12);ctx.stroke()}}}
function loop(t){if(state!=='jogando'){draw();return}let dt=Math.min(.04,(t-last)/1000);last=t;update(dt);draw();if(state==='jogando')run()}

// ===== NITRO, EFEITOS E HUD (novo) =====
function kmh(){return Math.round(speed*.5)}
function nitroStep(dt){nitroOn=!!(keys.nitro&&nitro>0&&nitroLock<=0);
if(nitroOn){nitro=Math.max(0,nitro-34*dt);if(nitro===0){nitroLock=1.2;toast('Nitro esgotado!')}}else{nitroLock-=dt;if(!keys.nitro)nitro=Math.min(100,nitro+14*dt)}
fxStep(dt)}
function fxStep(dt){const cx=car.x+car.w/2;
if(nitroOn||turbo>0){for(let i=0;i<2;i++)fx.push({x:cx+(i?7:-7),y:car.y+car.h,vx:(Math.random()-.5)*20,vy:90,life:0,max:.3,r:5,k:'f'})}
else if((keys.cima&&speed>20)||speed>400)fx.push({x:cx+(Math.random()-.5)*16,y:car.y+car.h,vx:(Math.random()-.5)*30,vy:50,life:0,max:.7,r:6,k:'s'});
fx.forEach(p=>{p.life+=dt;p.x+=p.vx*dt;p.y+=(p.vy+speed*.3)*dt});fx=fx.filter(p=>p.life<p.max&&p.y<H+20)}
function drawFx(){fx.forEach(p=>{const a=1-p.life/p.max;if(p.k==='f'){ctx.fillStyle=p.life<p.max/2?`rgba(25,211,255,${a})`:`rgba(255,122,26,${a})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r*a+1,0,7);ctx.fill()}else{ctx.fillStyle=`rgba(200,205,220,${a*.35})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r+p.life*14,0,7);ctx.fill()}})}
function hudTxt(label,val,x,al,col){ctx.textAlign=al;ctx.fillStyle='#8fa6c9';ctx.font='bold 10px Arial';ctx.fillText(label,x,16);ctx.fillStyle=col;ctx.font='bold 22px Arial';ctx.fillText(val,x,40)}
function drawHUD(){if(state==='inicio')return;ctx.save();ctx.fillStyle='#050a1ecc';ctx.fillRect(0,0,W,52);ctx.fillStyle='#19d3ff';ctx.fillRect(0,52,W,2);
hudTxt('PONTOS',Math.floor(score),12,'left','#fff');hudTxt('MOEDAS',raceCoins,W/2,'center','#ffc93c');hudTxt('KM/H',kmh(),W-12,'right',nitroOn?'#19d3ff':'#fff');
const bx=14,by=H-24,bw=W-28;ctx.fillStyle='#050a1ecc';ctx.fillRect(bx-4,by-18,bw+8,36);ctx.textAlign='left';ctx.fillStyle='#8fa6c9';ctx.font='bold 10px Arial';ctx.fillText('NITRO  (Espaço)',bx,by-6);ctx.fillStyle='#1b2540';ctx.fillRect(bx,by,bw,9);
const g=ctx.createLinearGradient(bx,0,bx+bw,0);g.addColorStop(0,'#19d3ff');g.addColorStop(1,'#7a5cff');ctx.fillStyle=nitroLock>0?'#ff7a1a':g;ctx.fillRect(bx,by,bw*nitro/100,9);ctx.restore()}
function draw(){drawScene();drawHUD()}
// ===== FIM NITRO =====
function decorX(){return Math.random()<.5?6+Math.random()*(ROAD_X-30):ROAD_X+ROAD_W+14+Math.random()*(ROAD_X-30)}
function applyTrack(){ROAD_W=tracks[cfg.track].rw;ROAD_X=(W-ROAD_W)/2}
function renderMenu(){const bar=v=>Math.round(Math.max(.08,Math.min(1,v))*100);
$('listaPistas').innerHTML=Object.entries(tracks).map(([id,t])=>{const d=difLabel(t);return `<button class="pista-card ${cfg.track===id?'ativo':''}" data-pista="${id}"><div class="mini" style="--g:${t.grass};--r:${t.road};--hw:${t.rw/280*26}%"></div><div class="info"><b>${esc(t.nome)}</b><span class="dif dif-${d}">${d}</span></div><div class="mets"><div>Tráfego<i><span style="width:${bar((t.dens-.8)/1.6)}%"></span></i></div><div>Velocidade<i><span style="width:${bar((t.spd-.8)/.6)}%"></span></i></div><div>Aperto<i><span style="width:${bar((280-t.rw)/80)}%"></span></i></div></div></button>`}).join('');
$('listaPistas').querySelectorAll('[data-pista]').forEach(b=>b.onclick=()=>{cfg.track=b.dataset.pista;applyTrack();renderMenu();draw()})}
function toMenu(){cancelAnimationFrame(rafId);state='inicio';$('telaFim').hidden=true;$('telaPausa').hidden=true;$('telaInicio').hidden=false;applyTrack();reset();renderMenu();draw()}
function readEd(){return{nome:$('cNome').value.trim()||'Minha pista',tema:$('cTema').value,dens:+$('cDens').value,spd:+$('cSpd').value,rw:+$('cRw').value}}
function updEd(){const e=readEd(),d=difLabel(e);$('vDens').textContent=e.dens.toFixed(1)+'x';$('vSpd').textContent=e.spd.toFixed(2)+'x';$('vRw').textContent=e.rw+'px';$('cDif').textContent=d;$('cDif').className='dif dif-'+d}
['cDens','cSpd','cRw','cTema'].forEach(id=>$(id).oninput=updEd);
$('cSalvar').onclick=()=>{const e=readEd(),b=tracks[e.tema],t={id:'c'+Date.now(),nome:e.nome,grass:b.grass,tree:b.tree,road:b.road,dens:e.dens,spd:e.spd,rw:e.rw};save.custom.push(t);tracks[t.id]=t;persist();renderCustom();renderMenu();toast('🛠️ Pista salva!')};
function renderCustom(){$('cLista').innerHTML=save.custom.length?save.custom.map(t=>`<div class="card"><h3>${esc(t.nome)}</h3><span class="dif dif-${difLabel(t)}">${difLabel(t)}</span><p class="muted">Obstáculos ${t.dens}x • Velocidade ${t.spd}x • Largura ${t.rw}px</p><button class="btn" data-j="${t.id}">▶ Jogar</button> <button class="btn" data-x="${t.id}">🗑️</button></div>`).join(''):'<p class="muted">Nenhuma pista criada ainda.</p>';
$('cLista').querySelectorAll('[data-j]').forEach(b=>b.onclick=()=>{cfg.track=b.dataset.j;renderMenu();document.querySelector('[data-tab=corrida]').click();start()});
$('cLista').querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{const id=b.dataset.x;save.custom=save.custom.filter(t=>t.id!==id);delete tracks[id];if(cfg.track===id)cfg.track='campo';persist();renderCustom();renderMenu()})}
addEventListener('keydown',e=>{if(e.key!=='Escape')return;if($('corrida').classList.contains('ativa')&&state==='jogando')return pause();if(!$('home').classList.contains('ativa'))document.querySelector('.voltar').click()});
$('btnCriar').onclick=()=>document.querySelector('[data-tab=criador]').click();$('btnMenuFim').onclick=toMenu;$('btnMenuJogo').onclick=toMenu;$('btnTela').onclick=()=>{document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{})};$('btnMenuPausa').onclick=toMenu;
$('btnIniciar').onclick=start;$('btnReiniciar').onclick=start;$('btnReiniciarFim').onclick=start;$('btnPausar').onclick=pause;$('btnContinuar').onclick=pause;applyTrack();reset();renderMenu();renderCustom();updEd();renderGarage();renderShop();renderProfile();draw();
})();
